Initialisation
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #1
Opened 2022-04-06 08:37 UTC by camillaume

2022-04-06 08:44 UTC, LuigiMenez approved these changes
It's good

2022-04-06 08:46 UTC, LuigiMenez requested changes
not reviewed by SM

2022-04-06 09:37 UTC, n-faycel submitted a review, later dismissed

2022-04-06 09:51 UTC, LuigiMenez submitted a review, later dismissed
It's good

2022-04-12 09:12 UTC, LoicBrassart requested changes
Please fix these minor Evils

2022-04-12 09:12 UTC, LoicBrassart commented on frontend/src/GlobalStyle.jsx
> +
From my experience, this means that Prettier and ESLint are *not* configured as needed

2022-04-12 09:12 UTC, LoicBrassart commented on package.json
> +    "styled-reset": "^4.3.4"
Nope: you don't need these packages at the project root ;-)

2022-04-12 09:13 UTC, LoicBrassart commented
@LuigiMenez Beware, there were things to spot in this PR, especially the packages in the root package.json ;-)

2022-04-12 10:22 UTC, n-faycel approved these changes

2022-04-12 13:10 UTC, LuigiMenez approved these changes
Ok for me.

2022-04-12 13:44 UTC, LoicBrassart approved these changes
No more Evils !

2022-04-12 15:31 UTC, merged