answers display creation
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #18
Opened 2022-04-21 14:01 UTC by Gonaline

2022-04-21 14:02 UTC, n-faycel submitted a review, later dismissed
ok for me!

2022-04-21 14:26 UTC, LuigiMenez commented on frontend/package.json
> +    "template-fullstack": "file:.."
Nop

2022-04-21 14:27 UTC, LuigiMenez requested changes
Not template fullstack in package.json

2022-04-21 14:32 UTC, n-faycel approved these changes
ok for me!

2022-04-21 14:36 UTC, LuigiMenez approved these changes
Ok for me

2022-04-21 15:21 UTC, LoicBrassart requested changes
Use a state (this case is complicated, I'll help)

2022-04-21 15:21 UTC, LoicBrassart commented on backend/package.json
> +    "template-fullstack": "file:.."
Nope.

2022-04-21 15:21 UTC, LoicBrassart commented on frontend/src/components/Buttons/Answer/index.jsx
> +  const answers = [];
Plz use a state instead

const  [answers, setAnswers] = useState([])
setAnswers(answers.sort(() => Math.random() - 0.5);)

2022-04-21 15:21 UTC, LoicBrassart commented on frontend/src/components/Buttons/Answer/index.jsx
> +  const answers = [];
const tmpAnswers = [...answers]

2022-04-27 07:15 UTC, LoicBrassart commented
- Fix conflicts
- Do you need help about this ? (answer on Slack or in person plz)

2022-04-27 12:51 UTC, LoicBrassart commented
Plz fix conflicts before assigning

2022-04-28 08:24 UTC, merged