correction css after fusion
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #19
Opened 2022-04-27 12:50 UTC by n-faycel

2022-04-27 12:52 UTC, remi59800 submitted a review, later dismissed
okay

2022-04-27 12:52 UTC, Gonaline approved these changes

2022-04-27 13:00 UTC, Gonaline submitted a review, later dismissed

2022-04-27 13:08 UTC, LuigiMenez submitted a review, later dismissed
Ok for me,

2022-04-27 16:48 UTC, LoicBrassart requested changes
You should never display a value which is not a state

2022-04-27 16:48 UTC, LoicBrassart commented on frontend/src/components/Buttons/Answer/index.jsx
> +    answers.push(correctAnswer);
Nope, use a state!

2022-04-28 08:43 UTC, LoicBrassart approved these changes
No moe Evil

2022-04-28 08:43 UTC, merged