031 dice shake
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #27
Opened 2022-04-28 15:28 UTC by Ashram939

2022-04-28 15:30 UTC, Gonaline submitted a review, later dismissed
ok for me

2022-04-29 06:33 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2022-04-29 06:36 UTC, LuigiMenez commented on frontend/src/components/Links/Play/style.jsx
> +      width: 40vh;
width in vh?

2022-04-29 06:39 UTC, LuigiMenez commented on frontend/src/pages/Home/style.jsx
> +    width: 40vh;
width in vh?

2022-04-29 06:42 UTC, LuigiMenez requested changes
No vh for width, and trying to import the fonts into react

2022-04-29 06:59 UTC, Gonaline approved these changes
ok for me

2022-04-29 09:41 UTC, LuigiMenez approved these changes
Ok for me

2022-04-29 09:52 UTC, LoicBrassart reviewed
Saw no Evil

2022-04-29 09:53 UTC, LoicBrassart approved these changes
(Misclick, it's alright)

2022-04-29 09:55 UTC, merged