018 pawn
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #40
Opened 2022-05-04 15:10 UTC by Gonaline

2022-05-04 15:12 UTC, Ashram939 approved these changes, later dismissed
ok for me!

2022-05-04 15:27 UTC, Ashram939 submitted a review, later dismissed
ok for me

2022-05-05 07:04 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-05-05 08:36 UTC, LoicBrassart requested changes
Now that you have the Context set in place, use it instead of props for data already in it

2022-05-05 08:36 UTC, LoicBrassart commented on frontend/src/components/Question/index.jsx
> +  categoryColor,
Are these informations not stored in the Context ? Passing them as props here is useless :(

2022-05-05 12:41 UTC, FrancoisSalmon approved these changes
ok for me

2022-05-05 22:58 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-06 09:51 UTC, LoicBrassart approved these changes
SnE

2022-05-06 10:55 UTC, merged