Created Header with link on rules and styled it
WildCodeSchool/2022-03-JS-Lille-project-2-g2-trivialpursuit pull request #6
Opened 2022-04-14 10:04 UTC by camillaume

2022-04-14 10:07 UTC, ValentinCop submitted a review, later dismissed

2022-04-14 10:11 UTC, LuigiMenez approved these changes, later dismissed
Ok

2022-04-14 12:07 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2022-04-14 15:13 UTC, ValentinCop submitted a review, later dismissed

2022-04-15 06:22 UTC, LoicBrassart approved these changes
SnE

2022-04-15 06:23 UTC, LoicBrassart approved these changes, later dismissed
SnE

2022-04-15 06:42 UTC, LuigiMenez approved these changes, later dismissed
Ok

2022-04-15 08:38 UTC, ValentinCop approved these changes, later dismissed

2022-04-15 10:58 UTC, LuigiMenez commented on frontend/src/App.jsx
> +             </Styled>
Attention to indentation

2022-04-15 11:05 UTC, LuigiMenez requested changes
Verified the configuration of prettier for indentation

2022-04-15 12:29 UTC, ValentinCop submitted a review, later dismissed

2022-04-15 12:53 UTC, ValentinCop approved these changes

2022-04-15 13:11 UTC, LuigiMenez approved these changes
Ok for me

2022-04-15 13:12 UTC, LoicBrassart approved these changes
No more Evil

2022-04-15 13:15 UTC, merged